cp /data/homes/cae28/BigWigs/Gt_Ct7_Mats_Cast_Pat_Extrareads.bw .
cp /data/homes/cae28/BigWigs/Gt_Ct7_Mats_CBA_Mat_Extrareads.bw .
cp /data/homes/cae28/BigWigs/Dl_Ct7_Mats_CBA_mat.bw .
cp /data/homes/cae28/BigWigs/Dl_Ct7_Mats_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CGI_PatHets_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CGI_PatHets_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CGI_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CGI_MatHets_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CB_Wts_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_BC_Wts_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_BC_Wts_Bl6_Mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CT7_PatHets_CBA_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CT7_PatHets_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CT7_MatHets_CBA_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CT7_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_CB_Wts_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_895_PatHets_Cast_mat_2reps.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_895_PatHets_Bl6_pat_2reps.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_895_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Gt_895_MatHets_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_BC_Wts_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CGI_PatHets_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CGI_PatHets_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CGI_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CGI_MatHets_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CB_Wts_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_CB_Wts_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_BC_Wts_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Wd_BC_Wts_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CT7_MatHets_CBA_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CT7_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CGI_PatHets_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CGI_PatHets_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CGI_MatHets_Cast_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CGI_MatHets_Bl6_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CB_Wts_Cast_mat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_CB_Wts_Bl6_pat.bw .
cp /data/homes/cae28/BigWigs/AST_Dl_BC_Wts_Cast_pat.bw .
