cp /data/homes/cae28/BigWigs/IG15_Liver_Pats.bw .
cp /data/homes/cae28/BigWigs/IG15_Liver_Mats.bw .
cp /data/homes/cae28/BigWigs/IG15_ESCs_Pats.bw .
cp /data/homes/cae28/BigWigs/IG15_ESCs_Mats.bw .
cp /data/homes/cae28/BigWigs/IG15_Brain_Pats.bw .
cp /data/homes/cae28/BigWigs/IG15_Brain_Mats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Liv_CB_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Liv_CB_Mats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Liv_BC_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Liv_BC_Mats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_ESCs_CB_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_ESCs_CB_Mats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_ESCs_BC_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_ESCs_BC_Mats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Br_CB_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Br_CB_Mats.bw . 
cp /data/homes/cae28/BigWigs/Gtl17_Br_BC_Pats.bw .
cp /data/homes/cae28/BigWigs/Gtl17_Br_BC_Mats.bw .
cp /data/homes/cae28/BigWigs/Dlk15_Liver_Pats.bw .
cp /data/homes/cae28/BigWigs/Dlk15_Liver_Mats.bw .
cp /data/homes/cae28/BigWigs/Dlk15_Brain_Pats.bw .
cp /data/homes/cae28/BigWigs/Dlk15_Brain_Mats.bw .
